In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from collections import Counter
from dadapy.metric_comparisons import MetricComparisons
from scipy.stats import rankdata
import pickle

import scienceplots
plt.style.use(['science','notebook'])

In [3]:
from scipy.spatial.distance import pdist, squareform

def nns_index_array(data, metric="euclidean", maxk=1):
    """
    Computes the indices of the k nearest neighbors to each point.

    Args:
        data (np.ndarray or list(list(float))): dataset of shape (N,D), with N points and D features
        metric (str, default="euclidean"): name of the distance employed
        maxk (int, default=1): number of nearest neighbors considered in the Information Imbalance calculation

    Returns:
        NNs (np.ndarray): array of shape (N,k). The ij-th element is the index of the j-th nearest 
                          neighbor to point i.
    """
    N = data.shape[0]

    pairwise_dist = squareform(pdist(data, metric=metric))
    pairwise_dist = pairwise_dist.astype('float')

    rank_matrix = rankdata(pairwise_dist, method='average', axis=1)
    
    NNs = np.zeros((N, maxk+1), dtype=int)
    for i in np.arange(N):
        NNs[i, :] = np.argpartition(rank_matrix[i], np.arange(maxk+1))[:maxk+1]
    return np.array(NNs)

In [4]:
genes_df = pd.read_csv("gene.yyy")
times_df = pd.read_csv("time.yyy")
print(genes_df.shape,times_df.shape)

(228, 3970) (3969, 2)

In [5]:
genes_df.T

,0,1,2,3,4,5,6,7,8,9,...,218,219,220,221,222,223,224,225,226,227
Unnamed: 0,CALML6,HTR6,PTAFR,PTGER3,PTGFR,PRKACB,MCOLN2,MCOLN3,NGF,CASQ2,...,ITPKC,CALM3,SLC8A2,GRIN2D,SPHK2,HRC,PRKCG,P2RX6,PDGFB,CACNA1I
EC2-AAACCTGAGGATGCGT,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.693147,0.0
EC2-AAAGCAAAGGTGTGGT,0.0,0.0,0.0,0.693147,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.693147,1.386294,0.0,0.0,0.0,1.386294,0.0,0.0,0.693147
EC2-AAAGCAACAGCTATTG,0.0,0.0,0.0,0.0,0.0,0.693147,0.0,0.0,0.0,0.0,...,0.0,1.098612,1.098612,0.0,0.0,0.0,0.693147,0.0,0.693147,0.0
EC2-AAATGCCAGAAGGTTT,0.0,0.0,0.0,0.693147,0.0,0.693147,0.0,0.0,0.0,0.693147,...,0.0,0.0,0.0,0.0,0.693147,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
EC10-TTTGGTTCAAAGGTGC,0.0,0.0,0.0,0.0,0.0,0.693147,0.0,0.0,0.0,0.0,...,0.0,0.693147,0.693147,0.0,0.0,0.0,0.693147,0.0,0.0,0.0
EC10-TTTGGTTTCATCACCC,0.0,0.0,0.0,0.0,0.0,0.693147,0.0,0.0,0.0,0.0,...,0.0,0.693147,0.693147,0.0,0.0,0.0,0.0,0.0,0.0,0.693147
EC10-TTTGTCAAGAATAGGG,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
EC10-TTTGTCAAGACGACGT,0.0,0.0,0.0,0.0,0.0,0.693147,0.0,0.0,0.0,0.0,...,0.0,0.693147,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.693147
EC10-TTTGTCACATCACAAC,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.693147,0.0,0.693147,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
times_df

                     Sample  Calcium Signaling Pseudotime
0      EC1-TGATTTCGTACAGCAG                      1.700983
1      EC1-CACTCCACAACGCACC                     13.145695
2      EC1-GGCCGATTCAACTCTT                      3.424308
3      EC2-GAGTCCGCAAGTAATG                      5.243402
4      EC1-TACAGTGGTAGAGGAA                      8.186124
...                     ...                           ...
3964  EC10-GGAAAGCCATACTACG                      9.191953
3965   EC9-CACAGGCGTTGGTGGA                     14.693694
3966  EC10-GCAAACTAGCGTGAAC                     13.426085
3967   EC8-CCACTACGTCCAACTA                     23.574981
3968  EC10-GCGCCAATCAGATAAG                      9.211148

[3969 rows x 2 columns]

In [7]:
# extract numpy arrays from pandas dataframes
times = times_df['Calcium Signaling Pseudotime'].to_numpy() + np.random.normal()
genes = (genes_df.T).iloc[1:,:].to_numpy(dtype=float)
print(times.shape, genes.shape)

(3969,) (3969, 228)

## Introduce noise to break degeneracy in the two spaces

In [12]:
# add noise to break neighbor degeneracies (both in gene and pseudotime spaces)
times += np.random.normal(loc=0., scale=1e-10, size=times.shape)
genes += np.random.normal(loc=0., scale=1e-6, size=genes.shape)

In [10]:
target_ranks_times = nns_index_array(times.reshape(-1,1), maxk=times.shape[0]-1)

## Greedy selection of best variables

In [13]:
k = 1
n_coords = 30
n_best = 1
njobs = 4

d = MetricComparisons(genes, njobs=njobs)
variables, imbalances, _ = d.greedy_feature_selection_target(target_ranks=target_ranks_times, 
                                                          n_best=n_best,
                                                          n_coords=n_coords,
                                                          k=k,
                                                          symm=False)

total number of computations is:  228
total number of computations is:  227
total number of computations is:  226
total number of computations is:  225
total number of computations is:  224
total number of computations is:  223
total number of computations is:  222
total number of computations is:  221
total number of computations is:  220
total number of computations is:  219
total number of computations is:  218
total number of computations is:  217
total number of computations is:  216
total number of computations is:  215
total number of computations is:  214
total number of computations is:  213
total number of computations is:  212
total number of computations is:  211
total number of computations is:  210
total number of computations is:  209
total number of computations is:  208
total number of computations is:  207
total number of computations is:  206
total number of computations is:  205
total number of computations is:  204
total number of computations is:  203
total number of computations is:  202
total number of computations is:  201
total number of computations is:  200
total number of computations is:  199

ValueError: too many values to unpack (expected 2)